-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  event_type text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  ip_address inet,
  user_agent text,
  referrer text,
  country text,
  city text,
  device_type text,
  browser text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT analytics_pkey PRIMARY KEY (id),
  CONSTRAINT analytics_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.analytics_usage (
  id bigint NOT NULL DEFAULT nextval('analytics_usage_id_seq'::regclass),
  user_id uuid NOT NULL,
  platform text NOT NULL CHECK (platform = ANY (ARRAY['instagram'::text, 'tiktok'::text])),
  date date NOT NULL DEFAULT CURRENT_DATE,
  count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT analytics_usage_pkey PRIMARY KEY (id),
  CONSTRAINT analytics_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.custom_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  url text NOT NULL,
  icon_url text,
  is_featured boolean DEFAULT false,
  status USER-DEFINED DEFAULT 'active'::link_status,
  click_count integer DEFAULT 0,
  display_order integer DEFAULT 0,
  scheduled_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT custom_links_pkey PRIMARY KEY (id),
  CONSTRAINT custom_links_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.instagram_analytics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  social_link_id uuid,
  instagram_id text NOT NULL,
  username text NOT NULL,
  full_name text,
  profile_pic_url text,
  biography text,
  external_url text,
  follower_count integer DEFAULT 0,
  following_count integer DEFAULT 0,
  media_count integer DEFAULT 0,
  engagement_rate numeric DEFAULT 0,
  is_private boolean DEFAULT false,
  is_verified boolean DEFAULT false,
  is_business_account boolean DEFAULT false,
  country text,
  city text,
  languages jsonb,
  topics jsonb,
  recent_posts jsonb,
  cached_timestamp bigint,
  last_post_at bigint,
  auto_update_enabled boolean DEFAULT true,
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  saved_username text,
  CONSTRAINT instagram_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT instagram_analytics_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT instagram_analytics_social_link_id_fkey FOREIGN KEY (social_link_id) REFERENCES public.social_links(id)
);
CREATE TABLE public.invite_codes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  code text NOT NULL UNIQUE,
  plan_type text NOT NULL,
  max_uses integer DEFAULT 1,
  current_uses integer DEFAULT 0,
  is_active boolean DEFAULT true,
  expires_at timestamp with time zone,
  used_by uuid,
  used_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT invite_codes_pkey PRIMARY KEY (id),
  CONSTRAINT invite_codes_used_by_fkey FOREIGN KEY (used_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  username text CHECK (char_length(username) >= 3),
  full_name text,
  tagline text,
  bio text,
  location text,
  pronouns text,
  avatar_url text,
  cover_url text,
  role USER-DEFINED DEFAULT 'content_creator'::user_role,
  plan USER-DEFINED DEFAULT 'basic'::user_plan,
  invitation_code text,
  niche text,
  is_verified boolean DEFAULT false,
  is_active boolean DEFAULT true,
  profile_views integer DEFAULT 0,
  total_clicks integer DEFAULT 0,
  last_active_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  birth_year integer,
  show_age boolean DEFAULT true,
  CONSTRAINT profiles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rate_limits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  identifier text NOT NULL,
  request_count integer DEFAULT 1,
  window_start timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rate_limits_pkey PRIMARY KEY (id)
);
CREATE TABLE public.showcase_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  video_url text NOT NULL,
  thumbnail_url text,
  platform text NOT NULL,
  view_count integer DEFAULT 0,
  like_count integer DEFAULT 0,
  click_count integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT showcase_items_pkey PRIMARY KEY (id),
  CONSTRAINT showcase_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.social_followers_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  social_link_id uuid NOT NULL,
  follower_count integer NOT NULL,
  scraped_at timestamp with time zone DEFAULT now(),
  source text DEFAULT 'manual'::text,
  CONSTRAINT social_followers_history_pkey PRIMARY KEY (id),
  CONSTRAINT social_followers_history_social_link_id_fkey FOREIGN KEY (social_link_id) REFERENCES public.social_links(id)
);
CREATE TABLE public.social_links (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  platform text NOT NULL,
  username text,
  url text NOT NULL,
  follower_count integer DEFAULT 0,
  followers_count integer DEFAULT 0,
  following_count integer DEFAULT 0,
  media_count integer DEFAULT 0,
  engagement_rate numeric DEFAULT 0,
  is_featured boolean DEFAULT false,
  is_verified boolean DEFAULT false,
  status USER-DEFINED DEFAULT 'active'::link_status,
  click_count integer DEFAULT 0,
  display_order integer DEFAULT 0,
  platform_icon text,
  custom_platform_name text,
  auto_followers boolean DEFAULT false,
  scrape_enabled boolean DEFAULT true,
  last_scraped_at timestamp with time zone,
  api_data jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT social_links_pkey PRIMARY KEY (id),
  CONSTRAINT social_links_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.tiktok_analytics (
  id bigint NOT NULL DEFAULT nextval('tiktok_analytics_id_seq'::regclass),
  user_id uuid NOT NULL UNIQUE,
  saved_username text,
  tiktok_uid text NOT NULL,
  unique_id text,
  nickname text,
  avatar text,
  follower_count bigint DEFAULT 0,
  region text,
  region_name text,
  signature text,
  verify_type text DEFAULT '0'::text,
  account_type text DEFAULT '0'::text,
  category_name text,
  category_id text,
  first_video_time text,
  show_shop_tab integer DEFAULT 0,
  is_shop_author integer DEFAULT 0,
  live_type integer DEFAULT 0,
  follower_count_show text,
  follower_28_count bigint,
  follower_28_count_show text,
  follower_28_last_count bigint,
  follower_28_count_rate text,
  region_rank bigint,
  region_rank_show text,
  last_region_rank bigint,
  region_rank_rate text,
  category_rank bigint,
  category_rank_show text,
  last_category_rank bigint,
  category_rank_rate text,
  flow_index bigint,
  carry_index bigint,
  aweme_28_count bigint,
  aweme_28_count_show text,
  live_28_count bigint,
  live_28_count_show text,
  last_video_time text,
  video_28_avg_play_count bigint,
  video_28_avg_play_count_show text,
  video_28_avg_interaction_count bigint,
  video_28_avg_interaction_count_show text,
  goods_28_avg_sole_count bigint,
  goods_28_avg_sole_count_show text,
  goods_28_avg_sale_amount numeric,
  live_28_avg_sold_count bigint,
  live_28_avg_sold_count_show text,
  live_28_avg_sale_amount numeric,
  analysis_step integer DEFAULT 0,
  analysis_status text DEFAULT 'pending'::text,
  auto_update_enabled boolean DEFAULT true,
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  follower_count_basic bigint DEFAULT 0,
  region_basic text DEFAULT ''::text,
  region_name_basic text DEFAULT ''::text,
  CONSTRAINT tiktok_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT tiktok_analytics_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  plan USER-DEFINED NOT NULL,
  started_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  is_active boolean DEFAULT true,
  invitation_code_used text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT user_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
